stages:
  - lint
  - build
  - deploy

default:
  before_script:
    - IMAGE_NAME=$(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]')

lint_helm:
  stage: lint
  image: matthiasgabathuler/my-runner:ubuntu-20.04
  script:
    - >-
      helm lint ${CI_PROJECT_DIR}/helm
      --set image.name=${IMAGE_NAME}
      --set image.tag=${CI_COMMIT_REF_NAME}
      --set build.job_id=${CI_JOB_ID}
      --set build.commit=${CI_COMMIT_SHA}

build_backend:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    IMAGE_NAME: $ci_registry/$CI_PROJECT_PATH-backend
  script:
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/backend-project"
      --dockerfile "${CI_PROJECT_DIR}/backend-project/Dockerfile"
      --destination "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
      --destination "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"
      --destination "${IMAGE_NAME}:latest"

build_frontend:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    IMAGE_NAME: $ci_registry/$CI_PROJECT_PATH-frontend
  script:
    - sed -i "s/##BACKEND_URI##/http:\/\/$(echo $CI_PROJECT_NAME | tr '[:upper:]' '[:lower:]').course-xai-iml22.isginf.ch\/backend/g" react-frontend/src/backend/BackendQueryEngine.tsx
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/react-frontend"
      --dockerfile "${CI_PROJECT_DIR}/react-frontend/Dockerfile"
      --destination "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
      --destination "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"
      --destination "${IMAGE_NAME}:latest"

deploy_app:
  stage: deploy
  image: matthiasgabathuler/my-runner:ubuntu-20.04
  variables:
    IMAGE_NAME: $CI_PROJECT_PATH
  script:
  - >-
    helm --namespace $k8s_namespace
    --kube-context $k8s_context
    upgrade ${CI_PROJECT_NAME} ${CI_PROJECT_DIR}/helm
    --install
    --history-max 5
    --set image.host=${ci_registry}
    --set image.name=${IMAGE_NAME}
    --set image.tag=${CI_COMMIT_REF_NAME}
    --set build.job_id=${CI_JOB_ID}
    --set build.commit=${CI_COMMIT_SHA}
  only:
    - ci-cd-pipeline
    - /^release.*$/
    - master
    - main